HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string Name { get; set; }
    public SpecialtyOptions Specialty { get; set; }
    public List<Client> Clients { get; set; }
    public List<Appointment> Appointments { get; set; }
  }

  public enum SpecialtyOptions
  {
    Wax,
    Spiky,
    Gel,
    Shmear,
    Twists,
    Braids,
    Color,
    Buzz,
    Trim,
    Bangs
  }
}

HairSalon/Controllers/AppointmentsController.cs
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class AppointmentsController : Controller
  {
    private readonly HairSalonContext _db;
    public AppointmentsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Appointment> appointments = _db.Appointments
                                    .Include(model => model.Client)
                                    .Include(model => model.Stylist)
                                    .ToList();
      return View(appointments);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      ViewBag.ClientId = new SelectList(_db.Clients, "ClientId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Appointment appointment)
    {
      _db.Appointments.Add(appointment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Appointment foundApt = _db.Appointments.Include(model => model.Client)
                                            .Include(model => model.Stylist)
                                            .FirstOrDefault(model => model.AppointmentId == id);
      return View(foundApt);
    }

    public ActionResult Edit(int id)
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      ViewBag.ClientId = new SelectList(_db.Clients, "ClientId", "Name");
      Appointment foundApt = _db.Appointments.FirstOrDefault(model => model.AppointmentId == id);
      return View(foundApt);
    }

    [HttpPost]
    public ActionResult Edit(Appointment appointment)
    {
      int id = appointment.AppointmentId;
      _db.Appointments.Update(appointment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Appointment foundApt = _db.Appointments.Include(model => model.Client)
                                      .Include(model => model.Stylist)
                                      .FirstOrDefault(model => model.AppointmentId == id);
      return View(foundApt);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Appointment foundApt = _db.Appointments.FirstOrDefault(model => model.AppointmentId == id);
      _db.Remove(foundApt);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/ClientController.cs
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;
    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> allStylists = _db.Stylists.ToList();
      ViewBag.AllStylistsList = allStylists;

      List<Client> allClients = _db.Clients.ToList();
      return View(allClients);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();

      List<Stylist> allStylists = _db.Stylists.ToList();
      ViewBag.AllStylistsList = allStylists;

      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client foundClient = _db.Clients.Include(client => client.Stylist).FirstOrDefault(client => client.ClientId == id);
      return View(foundClient);
    }

    public ActionResult Edit(int id)
    {
      Client foundClient = _db.Clients.Include(client => client.Stylist).FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(foundClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Clients.Update(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Client foundClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(foundClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client foundClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(foundClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;
    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> allStylists = _db.Stylists.ToList();
      return View(allStylists);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist foundStylist = _db.Stylists.Include(stylist => stylist.Clients)
                                          .Include(stylist => stylist.Appointments)
                                          .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(foundStylist);
    }

    public ActionResult Edit(int id)
    {
      Stylist foundStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId ==id);
      return View(foundStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Stylists.Update(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Stylist foundStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId ==id);
      return View(foundStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Stylist foundStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId ==id);
      _db.Stylists.Remove(foundStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Specialty)
  @Html.DropDownListFor(model => model.Specialty,
        new SelectList(Enum.GetNames(typeof(SpecialtyOptions))),
        "Select Specialty")

  <input type="submit" value="Add new stylist" />
}

<p>@Html.ActionLink("All Stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete @Model.Name?</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)
  <input class="btn" type="submit" value="Delete" />
}

@Html.ActionLink("Cancel", "Details", new { id = Model.StylistId }, new { @class="btn" })

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
<p>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)</p>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>

@if (Model.Clients.Count == 0)
{
  <p>Stylist has no clients.</p>
  <p>@Html.ActionLink("Add new client", "Create", "Clients")</p>
}
else
{
  <h3>Clients</h3>

  <table class="table-bordered">
    <tr>
      <th class="col">@Html.DisplayNameFor(model => model.Clients[0].Name)</th>
      <th class="col">@Html.DisplayNameFor(model => model.Clients[0].Phone)</th>
      <th class="col">@Html.DisplayNameFor(model => model.Clients[0].Email)</th>
    </tr>
    @foreach (Client client in Model.Clients)
    {
      <tr>
        <td>@Html.ActionLink($"{client.Name}", "Details", "Clients", new { id = client.ClientId } )</td>
        <td>@client.Phone</td>
        <td>@client.Email</td>
      </tr>
    }
  </table>
}

@if (Model.Appointments.Count == 0)
{
  <p>No upcoming appointments</p>
  <p>@Html.ActionLink("Add an appointment", "Create", "Appointments")</p>
}
else
{
    <h3>Appointments</h3>

  <table class="table-bordered">
    <tr>
      <th class="col">@Html.DisplayNameFor(model => model.Appointments[0].Date)</th>
      <th class="col">@Html.DisplayNameFor(model => model.Appointments[0].Time)</th>
      <th class="col">@Html.DisplayNameFor(model => model.Appointments[0].Client)</th>
    </tr>
    @foreach (Appointment appointment in Model.Appointments)
    {
      <tr>
        <td>@Html.ActionLink($"{appointment.Date.ToString("MM/dd/yyyy")}", "Details", "Appointments", new { id = appointment.AppointmentId } )</td>
        <td>@appointment.Time.ToString("hh':'mm")</td>
        @foreach (Client client in Model.Clients)
        {
          if (client.ClientId == appointment.ClientId)
          {
            <td>@client.Name</td>
          }
        }
      </tr>
    }
  </table>
}

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist
@using HairSalon.Models

<h2>Edit Stylist</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Specialty)
  @Html.DropDownListFor(model => model.Specialty,
          new SelectList(Enum.GetNames(typeof(SpecialtyOptions))),
          "Select Specialty")

  <input type="submit" value="Update Stylist" />
}

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models

@if (Model.Count == 0)
{
  <p>You have no stylists, yet.</p>
}

<ul>
@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}
</ul>

<p>@Html.ActionLink("Add a stylist", "Create" , null, null, new { @class="btn" })</p>